[package]
name = "agent-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.65"
shlex = "1.1.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
libc = "0.2.134"
tracing = { version = "0.1.36", default-features = false }
